# Specify sample list path
samples: "samples.txt"

# Specify metagenomes PE reads directory: MG_ID.R1.fq.gz, MG_ID.R2.fq.gz, MG_ID.unpaired.fq.gz
datadir: "path/to/PE/reads"

# Specify tools ressources
metaspades_threads: 8
metaspades_memory: 250
cp_threads: 4
cp_mem: 2

# Directory architecture (don't change)
assembly: "assembly"
contigs: "contigs"
graphs: "graphs"
stats: "stats"
logs: "logs"
slurm_logs: "logs/slurm"